# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 10

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    #col.active_border = rgba(89b4faee) rgba(74c7ecee) 45deg
    col.active_border = rgba(89b4faee) rgba(89b4faee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}
