# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

#$font = Adwaita Mono

general {
    hide_cursor = false
    deny = 10 
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    # bezier = overshot, 0.13, 0.99, 0.29, 1.05
    # animation = fadeIn, 1, 5, linear
    animation = fadeIn, 1, 5, linear
    # animation = fadeOut, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
}

input-field {
    monitor =
    size = 15%, 4%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    # outer_color = rgba(4c566aee) rgba(d8dee9ee) 45deg
    # check_color = rgba(d8dee9ee) rgba(ebcb8bee) 120deg
    outer_color = rgba(89b4faee) rgba(74c7ecee) 270deg
    check_color = rgba(89dcebee) rgba(94e2d5ee) 120deg
    fail_color = rgba(f38ba8ee) rgba(cba6f7ee) 40deg

    # font_color = rgba(e5e9f0ee)
    font_color = rgba(cdd6f4ee)
    fade_on_empty = false
    rounding = 26

    font_family = Ubuntu
    placeholder_text = 
    fail_text = 
    # fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.2

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0,30 
    halign = center
    valign = bottom
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 80
    #font_family = Fira Code
    font_family = Montserrat Medium
    # font_color = rgba(e5e9f0ee)
    color = rgba(cdd6f4ee)

    position = 0, -50
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 20
    #font_family = Fira Code
    font_family = Montserrat Medium
    font_color = rgba(cdd6f4ee)
    color = rgba(cdd6f4ee)

    position = 0, -200
    halign = center
    valign = top
}

label {
    monitor =
    #text = i use arch btw... 
    text = $USER
    #font_family = Fira Code
    font_family = Montserrat Medium
    font_size = 15
    color = rgba(cdd6f4ee)
    # onclick = hyprctl switchxkblayout all next

    position = 0, 90
    halign = center
    valign = bottom
}
#image {
#    monitor =
#    path = /home/chess/Pictures/Chicken.jpg
#    #path = /home/chess/Pictures/Chess.png
#    size = 150
#    rounding = 200 # no rounding
#    border_size = 0
#
#    position = 0, 120
#    halign = center
#    valign = bottom
#}
