#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox & swaync

#exec-once = waybar & swaync & hypridle & hyprpaper
exec-once = waybar & swaync & hypridle & awww-daemon &# hyprsunset &
exec-once = gamemoded -r &
#exec-once = printf %s\n "$HYPRLAND_INSTANCE_SIGNATURE" > /tmp/his.log
#exec-once = notify-send ""

#exec = gsettings set org.gnome.desktop.interface gtk-theme "Graphite-Dark"   # for GTK3 apps
#exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
#
#env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
