##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#windowrulev2 = float, center, title:^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename), class:^(.*)$
windowrule {
    name = float-file
    match:class = .*
    match:title = Open File|Open Files|Open|Save|Save As|Export|Import|Choose File|Rename|satty
    center = yes
    float = yes
}
layerrule {
    name = blur
    match:namespace = swaync-control-center|rofi|swaync-notification-window
    blur = yes
    ignore_alpha = .2
}
#|logout_dialog
layerrule {
    name = logout-blur
    match:namespace = logout_dialog
    blur = yes
    ignore_alpha = .2
    animation = popin 85%
    dim_around = yes
}
layerrule {
    name = rofi-blur-around
    match:namespace = rofi
    dim_around = yes
    animation = popin 85%
}
layerrule {
    name = swaync-animation
    match:namespace = swaync-control-center|swaync-notification-window
    animation = slide: right
}
layerrule {
    name = blur-waybar
    match:namespace = waybar
    blur = yes
    ignore_alpha = .3
}
